### ISSUE TITLE
Applying styles

### ISSUE THREAD

**Issue by davidgraeff** [oom-components/page-loader#1]
Hey, thanks for this well written module.

The style replacement does not work reliable for me though. (as in: it works 90%, but in 1/10 cases my page is completely un-styled. Chrome 70.)

If I look at the source here:
https://github.com/oom-components/page-loader/blob/ced66b24b84187dafd0a01155e9d848e49478417/src/page.js#L136

You are completely removing all styles and adding styles again. Could you consider to only remove removed ones and add new ones. That way a "base" style would always be in place and even if chrome decides not to apply page specific style, the page doesn't break completely.

Thanks, David

**Comment by oscarotero** [comment]
Hi.
That code remove and add inlined styles (the `<style>` tag). Are you using only inlined styles in your project?

**Comment by davidgraeff** [comment]
You are right, never mind. I'm using referenced styles only and you are not touching those apparently if src (href?) hasn't changed. Need to look for another reason that might cause this behaviour (I'm also using webcomponents with shadow Dom for the first time on that page.)

**Comment by oscarotero** [comment]
I'm using this library in projects like this: https://historia-arte.com/ and here is the source code: https://github.com/oscarotero/ha/blob/master/assets/js/modules/page-loader.js (not the recent version, but this part doesn't change) and never fail to me.
Maybe the reason is not this library itself, but another javascript executed when the page is loaded that throws an exception and makes the rest of javascript to fail. For this reason, it's recomended to use a try/catch and the `fallback()` function to mitigate these cases and ensure the new page is loaded.

**Comment by davidgraeff** [comment]
Indeed. Thx.
